<a href="https://colab.research.google.com/github/trndnhan/UTI-Analysis-and-Binary-Classification/blob/main/notebooks/1_Pre_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import Libraries and Dataset

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Work/Data/urinalysis_tests.csv')
df

,Unnamed: 0,Age,Gender,Color,Transparency,Glucose,Protein,pH,Specific Gravity,WBC,RBC,Epithelial Cells,Mucous Threads,Amorphous Urates,Bacteria,Diagnosis
0,0,76.00,FEMALE,LIGHT YELLOW,CLEAR,NEGATIVE,NEGATIVE,5.0,1.010,1-3,0-2,OCCASIONAL,RARE,NONE SEEN,OCCASIONAL,NEGATIVE
1,1,9.00,MALE,DARK YELLOW,SLIGHTLY HAZY,NEGATIVE,1+,5.0,1.030,1-3,0-2,RARE,FEW,FEW,MODERATE,NEGATIVE
2,2,12.00,MALE,LIGHT YELLOW,SLIGHTLY HAZY,NEGATIVE,TRACE,5.0,1.030,0-3,0-2,RARE,FEW,MODERATE,RARE,NEGATIVE
3,3,77.00,MALE,BROWN,CLOUDY,NEGATIVE,1+,6.0,1.020,5-8,LOADED,RARE,RARE,NONE SEEN,FEW,NEGATIVE
4,4,29.00,FEMALE,YELLOW,HAZY,NEGATIVE,TRACE,6.0,1.025,1-4,0-2,RARE,RARE,NONE SEEN,FEW,NEGATIVE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,1431,0.06,MALE,YELLOW,CLEAR,NEGATIVE,NEGATIVE,6.0,1.015,1-2,0-1,RARE,FEW,NONE SEEN,RARE,NEGATIVE
1432,1432,42.00,MALE,YELLOW,CLEAR,NEGATIVE,NEGATIVE,6.5,1.010,0-2,0-2,RARE,NONE SEEN,NONE SEEN,RARE,NEGATIVE
1433,1433,47.00,FEMALE,DARK YELLOW,CLEAR,NEGATIVE,TRACE,6.0,1.030,2-4,0-2,MODERATE,MODERATE,NONE SEEN,RARE,NEGATIVE
1434,1434,57.00,FEMALE,DARK YELLOW,CLEAR,NEGATIVE,TRACE,5.0,1.030,0-2,0-2,PLENTY,PLENTY,NONE SEEN,FEW,NEGATIVE
1435,1435,3.00,MALE,YELLOW,CLEAR,NEGATIVE,NEGATIVE,6.0,1.020,0-1,0-2,RARE,RARE,NONE SEEN,RARE,NEGATIVE

#Data Inspection

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1436 non-null   int64
 1   Age               1436 non-null   float64
 2   Gender            1436 non-null   object
 3   Color             1435 non-null   object
 4   Transparency      1436 non-null   object
 5   Glucose           1436 non-null   object
 6   Protein           1436 non-null   object
 7   pH                1436 non-null   float64
 8   Specific Gravity  1436 non-null   float64
 9   WBC               1436 non-null   object
 10  RBC               1436 non-null   object
 11  Epithelial Cells  1436 non-null   object
 12  Mucous Threads    1436 non-null   object
 13  Amorphous Urates  1436 non-null   object
 14  Bacteria          1436 non-null   object
 15  Diagnosis         1436 non-null   object
dtypes: float64(3), int64(1), object(12)
memory usage: 179.6+ KB

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, Age, Gender, Color, Transparency, Glucose, Protein, pH, Specific Gravity, WBC, RBC, Epithelial Cells, Mucous Threads, Amorphous Urates, Bacteria, Diagnosis]
Index: []

# Data Pre-processing

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.rename(columns=lambda x: x.replace(" ", "_"), inplace=True)

In [ ]:
df = df.drop(columns=['Unnamed:_0'])

In [ ]:
matched_values = df['WBC'].isin(df['RBC'])
matched_values_unique = df.loc[matched_values, 'WBC'].unique().tolist()
matched_values_unique

['1-3',
 '0-3',
 '5-8',
 '1-4',
 '3-5',
 '0-2',
 '1-2',
 '2-4',
 '6-8',
 '8-10',
 '10-12',
 '0-1',
 '4-6',
 '20-25',
 '25-30',
 '18-25',
 '3-6',
 'LOADED',
 '28-30',
 '5-7',
 '12-15',
 '30-35',
 '8-12',
 '2-3',
 '9-11',
 '>50',
 '20-22',
 '18-20',
 'TNTC',
 '2-5',
 '23-25',
 '5-10',
 '13-15',
 '0-4',
 '>100',
 '1-5',
 '4-10']

In [ ]:
unmatched_values_wbc = df.loc[~df['WBC'].isin(df['RBC']), 'WBC'].unique().tolist()
unmatched_values_wbc

['70-75',
 '15-17',
 '35-40',
 '50-55',
 '11-15',
 '48-55',
 '45-50',
 '12-14',
 '14-16',
 '17-20',
 '55-58',
 '15-20',
 '7-9',
 '34-36',
 '30-32',
 '9-15',
 '4-8',
 '11-14',
 '10-16',
 '7-15',
 '7-8',
 '15-22',
 '15-21',
 '7-10',
 '15-28',
 '4-5',
 '2-7',
 '3-7',
 '10-15',
 '4-7',
 '79-85',
 '28-35',
 '3-10',
 '5-6',
 '3-4',
 '15-18',
 '10-18',
 '8-11']

In [ ]:
unmatched_values_rbc = df.loc[~df['RBC'].isin(df['WBC']), 'RBC'].unique().tolist()
unmatched_values_rbc

['6-14',
 '9-12',
 '18-22',
 '18-21',
 '11-13',
 '16-18',
 '36-38',
 '85-87',
 '0-0',
 '22-24',
 '1-6',
 '48-62',
 '12-17',
 '2-6',
 '25-32',
 '38-40']

In [ ]:
def transform_wrbc(value):
    if '>' in value:
        return int(value.replace('>', ''))
    elif value == 'LOADED':
        return 150
    elif value == 'TNTC':
        return 200
    else:
        range_values = value.split('-')
        return (int(range_values[0]) + int(range_values[1])) / 2

df['WBC'] = df['WBC'].apply(transform_wrbc)
df['RBC'] = df['RBC'].apply(transform_wrbc)

In [ ]:
sorted(df['Age'].unique())[:13]

[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 1.0, 2.0]

In [ ]:
def transform_age(age):
    if age < 1:
        return age * 100 / 12
    else:
        return age

df['Age'] = df['Age'].apply(transform_age)

#Export cleaned data

In [ ]:
df.to_csv('/content/drive/MyDrive/Work/Data/cleaned_urinalysis_tests.csv', index=False)